# Generated by Django 3.2.9 on 2022-07-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='slug',
            field=models.SlugField(blank=True, max_length=35, null=True),
        ),
    ]
